name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: CI
    uses: ./.github/dougdodson/github-actions-workshop/reusable-build.yml@main
    with:
      dotnet_version: 9.0.x